# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [2]:
import numpy as np
arr =np.random.randint(10,23,23)
print(arr)

[21 19 18 10 19 15 21 15 18 20 15 14 20 12 22 15 19 15 21 14 20 22 22]


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [5]:
sp =np.arange(1,50,2)
print(sp)
print("length is:", len(sp))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
length is: 25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [6]:
num =np.linspace(4,7,27)
print(num)

[4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [7]:
mp = np.random.randn(5,4)
print("matrix is: \n",mp)
roundoff_matrix = np.round(mp,2)
print("rounded matrix is: \n", roundoff_matrix)


matrix is: 
 [[-0.27902908 -0.40939658  0.72230109  0.29212202]
 [-1.02370858  1.1897118   0.15946328  0.05427197]
 [ 0.03133768  1.67599297  1.6716068   1.13827195]
 [-0.80605774 -0.45591473 -0.40644498  1.20068824]
 [-0.75343756  0.81161337 -0.18105718 -0.07592316]]
rounded matrix is: 
 [[-0.28 -0.41  0.72  0.29]
 [-1.02  1.19  0.16  0.05]
 [ 0.03  1.68  1.67  1.14]
 [-0.81 -0.46 -0.41  1.2 ]
 [-0.75  0.81 -0.18 -0.08]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [8]:
n1 = np.random.randint(5,15,(5,5))
print(n1)


[[10 12 13 11 10]
 [ 8  6  9  5  5]
 [ 9 12  6  9 11]
 [13  8  6 13  7]
 [ 8  7  6 14  5]]


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [9]:
ar1 = np.zeros(14, dtype=int)
print(ar1)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [10]:
d2 = np.ones((2,4), dtype=float)
print(d2)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [11]:
a = np.array([[9,25,50,34,45], [3,34,34,65,2], [5,7,3,76,3], [7,8,6,54,6], [23,12,8,5,8]])
print(a)
print(a.shape)
print(type(a))
print(a.dtype)


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
(5, 5)
<class 'numpy.ndarray'>
int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [12]:
a = np.array([[9,25,50,34,45], [3,34,34,65,2], [5,7,3,76,3], [7,8,6,54,6], [23,12,8,5,8]])
print(a)
d =a.flatten()
center =d[int(len(d)/2)]
print("Center pixel for the matrix is ", center)


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
Center pixel for the matrix is  3


#### 10. Print the all the elements of 3rd row of the matrix

In [14]:
print("row3:", a[[2], :])


row3: [[ 5  7  3 76  3]]


#### 11. Print the all the elements of 4th columns of the matrix

In [15]:
print("column4:", a[:,[3]])


column4: [[34]
 [65]
 [76]
 [54]
 [ 5]]


#### 12. Print the 4 corner pixels of the matrix

In [16]:
max3 =a[[0,-1]][:,[0,-1]]
print(max3)


[[ 9 45]
 [23  8]]


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [17]:
m1 =a[:2,2:4]
print("m1: \n",m1)

m2 =a[3:,0:2]
print("m2: \n",m2)

m3 =a[2:,2:5]
print("m3: \n",m3)


m1: 
 [[50 34]
 [34 65]]
m2: 
 [[ 7  8]
 [23 12]]
m3: 
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [18]:
reshaped_m1 =m1.flatten()
print("Reshaped M1: ",reshaped_m1)
reshaped_m2 =m2.flatten()
print("Reshaped M2: ",reshaped_m2)
reshaped_m3 =m3.flatten()
print("Reshaped M3: ",reshaped_m3)


Reshaped M1:  [50 34 34 65]
Reshaped M2:  [ 7  8 23 12]
Reshaped M3:  [ 3 76  3  6 54  6  8  5  8]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [19]:
vertical=np.vstack((m1,m2))
horizontal=np.hstack((m1,m2))

print("Vertical matrix is: \n",vertical)
print("Horizontal matrix is: \n",horizontal)

Vertical matrix is: 
 [[50 34]
 [34 65]
 [ 7  8]
 [23 12]]
Horizontal matrix is: 
 [[50 34  7  8]
 [34 65 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [20]:
print("matrix add: \n",np.add(m1,m2))
print("matrix subtract: \n",np.subtract(m1,m2))
print("matrix multiplication: \n",np.matmul(m1,m2))
print("matrix divide: \n",np.divide(m1,m2))


matrix add: 
 [[57 42]
 [57 77]]
matrix subtract: 
 [[43 26]
 [11 53]]
matrix multiplication: 
 [[1132  808]
 [1733 1052]]
matrix divide: 
 [[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [22]:
r1 =np.delete(m3,0,0)
r1 =np.delete(r1,2,1)
print("new m3: \n", r1)
print("m1+m3: \n",m1+r1)


new m3: 
 [[ 6 54]
 [ 8  5]]
m1+m3: 
 [[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [23]:
me1 =m1[:,0].mean()
me2 =m2[:,1].mean()
matrixme =np.array([[me1,me2]])
m4 =np.concatenate((m1,matrixme),axis=0)
print("m4: \n", m4)


m4: 
 [[50. 34.]
 [34. 65.]
 [42. 10.]]


#### 19. Perform the matrix multiplication between m3 and m4

In [24]:
print("matrix multiplication: \n", np.matmul(m3,m4))


matrix multiplication: 
 [[2860. 5072.]
 [2388. 3774.]
 [ 906.  677.]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [25]:
bm1 =np.mean(a,axis=1)[0]
bm2 =np.mean(a,axis=1)[1]
bm3 =np.mean(a,axis=1)[2]
bm4 =np.mean(a,axis=1)[3]
bm5 =np.mean(a,axis=1)[4]
mean =np.vstack([bm1,bm2,bm3,bm4,bm5])
print("mean: \n", mean)

w1 =np.var(a,axis=1)[0]
w2 =np.var(a,axis=1)[1]
w3 =np.var(a,axis=1)[2]
w4 =np.var(a,axis=1)[3]
w5 =np.var(a,axis=1)[4]
var =np.vstack([w1,w2,w3,w4,w5])
print("var: \n", var)


dx1 =np.std(a,axis=1)[0]
dx2 =np.std(a,axis=1)[1]
dx3 =np.std(a,axis=1)[2]
dx4 =np.std(a,axis=1)[3]
dx5 =np.std(a,axis=1)[4]
std =np.vstack([dx1,dx2,dx3,dx4,dx5])
print("std: \n", std)

print("min mean:" ,np.min(mean))
print("max mean:" ,np.max(mean))
print("min var:" ,np.min(var))
print("max var:" ,np.max(var))
print("min std:" ,np.min(std))
print("max std:" ,np.max(std))


mean: 
 [[32.6]
 [27.6]
 [18.8]
 [16.2]
 [11.2]]
var: 
 [[214.64]
 [548.24]
 [820.16]
 [357.76]
 [ 39.76]]
std: 
 [[14.65059726]
 [23.41452541]
 [28.63843571]
 [18.91454467]
 [ 6.30555311]]
min mean: 11.2
max mean: 32.6
min var: 39.760000000000005
max var: 820.1600000000001
min std: 6.305553108173779
max std: 28.63843571147


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [26]:
runs =np.array([[54,60,10,65], [102,2,78,32], [3,110,1,92], [56,6,12,42], [12,8,22,11]])
balls =np.array([[50,42,22,78], [95,8,65,43], [9,100,7,101], [27,3,11,31], [24,20,36,27]])

Msd =np.average(runs, axis=1)[0]
Kholi =np.average(runs, axis=1)[1]
Rohit =np.average(runs, axis=1)[2]
Rahul =np.average(runs, axis=1)[3]
Dhawan =np.average(runs, axis=1)[4]
avg =np.vstack([Msd,Kholi,Rohit,Rahul,Dhawan])
print("average for each player: \n", avg)
print("descending order for player's average: \n", np.sort(avg, axis=0)[::-1])

Msrun =np.sum(runs, axis=1)[0]
Msball =np.sum(balls, axis=1)[0]
Khrun =np.sum(runs, axis=1)[1]
Khball =np.sum(balls, axis=1)[1]
Rhrun =np.sum(runs, axis=1)[2]
Rhball =np.sum(balls, axis=1)[2]
Rlrun =np.sum(runs, axis=1)[3]
Rlball =np.sum(balls, axis=1)[3]
Dhrun =np.sum(runs, axis=1)[4]
Dhball =np.sum(balls, axis=1)[4]

totalrun =np.vstack([Msrun,Khrun,Rhrun,Rlrun,Dhrun])
totalball =np.vstack([Msball,Khball,Rhball,Rlball,Dhball])
strikerate =np.divide(totalrun,totalball)*100
print("strikerate for each player: \n", strikerate)
print("descending order for player's strike rate: \n", np.sort(strikerate, axis=0)[::-1])


average for each player: 
 [[47.25]
 [53.5 ]
 [51.5 ]
 [29.  ]
 [13.25]]
descending order for player's average: 
 [[53.5 ]
 [51.5 ]
 [47.25]
 [29.  ]
 [13.25]]
strikerate for each player: 
 [[ 98.4375    ]
 [101.42180095]
 [ 94.93087558]
 [161.11111111]
 [ 49.53271028]]
descending order for player's strike rate: 
 [[161.11111111]
 [101.42180095]
 [ 98.4375    ]
 [ 94.93087558]
 [ 49.53271028]]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [27]:
marks =np.array([65,84,47,56,89,98,48,77,80,39])
passed =(marks[:]>=50).sum()
failed =(marks[:]<=50).sum()
print("no of students passed:", passed)
print("no of students failed:", failed)


no of students passed: 7
no of students failed: 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [28]:
marks =np.array([65,84,47,56,89,98,48,77,80,39])
print("Initial student marks:",marks)
print("students passed:",(marks>=50).sum(), ", students failed:",((marks)<50).sum())
tot= len(marks)
passrate= np.divide(passed,tot)*100
print("initial class pass percentage:", passrate)

for i in range(0,tot):
    if(((marks[i]>45)&(marks[i]<49))|(marks[i]>80)):
        marks[i]=marks[i]+5
        if (marks[i]>=100):
            marks[i]=100
            
print("New array obtained after mercy marks:",marks)
newpassvalue= (marks[:]>=50).sum()
newpassrate= np.divide(newpassvalue,tot)*100
print("students passed:",(marks>=50).sum(), ", students failed:",((marks)<50).sum())
print("new class pass percentage:",newpassrate)
print("increase in class percentage:",newpassrate-passrate)


Initial student marks: [65 84 47 56 89 98 48 77 80 39]
students passed: 7 , students failed: 3
initial class pass percentage: 70.0
New array obtained after mercy marks: [ 65  89  52  56  94 100  53  77  80  39]
students passed: 9 , students failed: 1
new class pass percentage: 90.0
increase in class percentage: 20.0


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [31]:
import time
def lis():
    axa = list(range(1,60000))
    byb = list(range(1,60000))
    fin = []
    for i in range(len(axa)):
        fin.append(((axa[i]**2)+8)/byb[i])

def nump():
    axa2 = np.array(range(1,60000))
    byb2 = np.array(range(1,60000))
    fin = ((axa2**2)+8)/byb2
st_time = time.time()
%time lis()
end_time = time.time()
print("The time taken to perform the operation by list is:", end_time-st_time)
st2_time = time.time()
%time nump()
end2_time = time.time()
print("The time taken to perform the operation by numpy is:", end2_time-st2_time)

Wall time: 64.1 ms
The time taken to perform the operation by list is: 0.06414341926574707
Wall time: 29.9 ms
The time taken to perform the operation by numpy is: 0.029888629913330078


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [32]:
#https://github.com/anjan12345678/python
'''NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.'''

'NumPy is a Python library used for working with arrays.\nIt also has functions for working in domain of linear algebra, fourier transform, and matrices.'